# Generated by Django 3.0.6 on 2020-11-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_auto_20201108_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000000),
        ),
    ]
