# Generated by Django 3.0.6 on 2020-11-08 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgers', '0003_auto_20201108_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
